#[derive(Debug, Clone)]
#[derive(PartialEq)]
pub enum Token {
    // holdings
    Identifier(String),
    funcName(String),
    structName(String),
    Integer(i32),
    Bool(bool),
    Null,
    // Keywords
    kwInt,
    kwBool,
    kwVoid,
    kwStruct,
    kwFunc(i32),
    kwBreak(i32),
    kwReturn(i32),
    kwIf(i32),
    kwElIf(i32),
    kwElse(i32),
    kwWhile(i32),
    kwPrint(i32),
    kwVarDec(i32),
   // kwStmnt,
    kwBlock,
    kwCall,
    kwNew,
    kwSet(i32),
    // opps
    lParen,
    rParen,
    Plus,
    Minus,
    Star,
    Div,
    Equals,
    Not,
    NotEquals,
    Semicolon,
    And,
    Or,
    Less,
    Great,
    LessEqual,
    GreatEqual,
    Collect,
    Eof,
}

pub trait TokenTrait {
    fn toString(&self) -> String;
}

impl Token {
    pub fn toString(&self) -> String {
        match self {
            Token::Identifier( s) => s.clone(),
            Token::funcName( s) => s.clone(),
            Token::structName( s) => s.clone(),
            Token::Integer(i) => i.to_string(),
            Token::Bool(b) => b.to_string(),
            Token::Null => "null".to_string(),
            Token::kwInt => "int".to_string(),
            Token::kwBool => "bool".to_string(),     
            Token::kwVoid => "void".to_string(),
            Token::kwStruct => "struct".to_string(),
            Token::kwFunc(n) => "func".to_string(),
            Token::kwBreak(n) => "break".to_string(),
            Token::kwReturn(n) => "return".to_string(),
            Token::kwIf(n) => "if".to_string(),
            Token::kwElIf(n) =>"elif".to_string(),
            Token::kwElse(n) =>"else".to_string(),
            Token::kwWhile(n) => "while".to_string(),
            Token::kwPrint(n) => "println".to_string(),
            Token::kwVarDec(n) => "vardec".to_string(),
            //Token::kwStmnt => "stmnt".to_string(),
            Token::kwBlock => "block".to_string(),
            Token::kwCall => "call".to_string(),
            Token::kwNew => "new".to_string(),
            Token::kwSet(i32) => "set".to_string(),
            Token::lParen => "(".to_string(),
            Token::rParen => ")".to_string(),
            Token::Plus => "+".to_string(),
            Token::Minus => "-".to_string(),
            Token::Star => "*".to_string(),
            Token::Div => "/".to_string(),
            Token::Equals => "==".to_string(),
            Token::Not => "!".to_string(),
            Token::NotEquals => "!=".to_string(),
            Token::Semicolon => ";".to_string(),
            Token::And => "and".to_string(),
            Token::Or => "or".to_string(),
            Token::Less => "<".to_string(),
            Token::Great => ">".to_string(),
            Token::LessEqual => "<=".to_string(),
            Token::GreatEqual => ">=".to_string(),
            Token::Collect => "collect".to_string(),
            Token::Eof => "EOF".to_string(),
        }
    }
}
